### ISSUE TITLE
Mypy complains when `[]` is used for `__slots__` definition

### ISSUE THREAD

**Issue by sobolevn** [python/mypy#10870]
**Bug Report**

Slot definition in a form of `__slots__ = []` raise an error:

```
ex.py:2: error: Need type annotation for "__slots__" (hint: "__slots__: List[<type>] = ...")
```

**To Reproduce**

Run `mypy` on this code:

```python
class A:
    __slots__ = []
```

**Expected Behavior**
I expect it to have the same effect as:

```python
class A:
    __slots__ = ()
```

and to produce no errors.
Moreover, `mypy` already knows that `__slots__` should contain `str` items only as shown here:

```python
class A:
    __slots__ = [1, 2]
```

Outputs:

```
ex.py:2: error: List item 0 has incompatible type "int"; expected "str"
ex.py:2: error: List item 1 has incompatible type "int"; expected "str"
```

Refs https://github.com/willmcgugan/rich/pull/1364

**Comment by sobolevn** [comment]
I would love to fix this. PR is incomming! 👍

**Comment by sobolevn** [comment]
Ok, we can generalize this problem to this case:

```python
from typing import List

class Super:
    a: List[int]

class Child(Super):
    a = []
```

The question is: should partial type be resolved in this general case? If yes, than I can modify the type checker to do it.
If not, should `__slots__` be the special case? If yes, what other props should be special cased?

**Comment by smheidrich** [comment]
#13494 which, AFAICT, should have fixed the generalized case mentioned by @sobolevn has been merged by now, but this is still broken for `__slots__` specifically, I guess because `__slots__` was removed from `object` again in https://github.com/python/typeshed/pull/6800?

**Comment by herebebeasties** [comment]
This is breaking default protobuf generated code type checking which is a shame. (See mentioned issues above.) Would be lovely to get this sorted out. 👍🏻
