### ISSUE TITLE
Callable ClassVar is incorrectly treated as a method

### ISSUE THREAD

**Issue by NeilGirdhar** [python/mypy#11077]
```python
from typing import Callable, MutableMapping, ClassVar

class C:
    x: ClassVar[Callable[[], MutableMapping]] = dict
    def f(self) -> MutableMapping:
        return self.x()  

c = C()
print(c.f())
```
Gives
```
a.py:6: error: Attribute function "x" with type "Callable[[], MutableMapping[Any, Any]]" does not accept self argument
```

**Comment by sobolevn** [comment]
This is a known problem / feature. The same happens without `ClassVar` as well: 

```python
from typing import Callable, MutableMapping, ClassVar

class C:
    x: Callable[[], MutableMapping] = dict
    def f(self) -> MutableMapping:
        # error: Attribute function "x" with type "Callable[[], MutableMapping[Any, Any]]" does not accept self argument
        return self.x()

c = C()
print(c.f())
```

Related https://github.com/python/mypy/issues/9489

**Comment by thejcannon** [comment]
FWIW #9489 was fixed by https://github.com/python/mypy/pull/10548. But this appears to still be an issue

**Comment by AlexWaygood** [comment]
Closing as a duplicate of #6910

**Comment by h4l** [comment]
Can we re-open this? It's not fixed and not a duplicate of #6910. The related issue for instance vars was fixed, but it remains a problem for `ClassVar[Callable[...]]`.

**Comment by thejcannon** [comment]
Blast from the past! 

FWIW there's a recent ongoing Discourse discussion about this

https://discuss.python.org/t/when-should-we-assume-callable-types-are-method-descriptors/92938
