### ISSUE TITLE
str-bytes-safe with new Formatted string literals

### ISSUE THREAD

**Issue by beauxq** [python/mypy#11806]
with this code:

`f"{b'def'}"`

I get this from mypy:

`On Python 3 '{}'.format(b'abc') produces "b'abc'", not 'abc'; use '{!r}'.format(b'abc') if this is desired behavior  [str-bytes-safe]`

That message doesn't make it clear whether there's any issue with my code, because it's about a different string formatting.
And if it is an issue, it doesn't tell me what formatted string literal to use if this is desired behavior.

**Comment by sobolevn** [comment]
Should be fixed in `0.920` (or in `0.930`). Works correctly on `master`:
<img width="752" alt="Снимок экрана 2021-12-22 в 12 27 10" src="https://user-images.githubusercontent.com/4660275/147069644-6f529e65-39fd-486b-9012-a7e02c1a4e13.png">

**Comment by beauxq** [comment]
That still doesn't make sense for an output message.
How is someone supposed to use `"{!r}"` with bytes in a formatted string literal?
We're not formatting `b'abc'` with `{}`, because the bytes are **inside** the curly braces.

**Comment by sobolevn** [comment]
Any suggestions?

**Comment by beauxq** [comment]
What is the code that you would suggest someone replace this with, if they want the output that this gives?

```python3
b = b'abc'
s = f"{b}"
print(s)
```

**Comment by beauxq** [comment]
I think my suggestion would be that `[str-bytes-safe]` only applies to this:

`"{}".format(b)`

and should not say anything about this:

`f"{b}"`

**Comment by Syndace** [comment]
Why is this closed? I still don't know how to avoid the warning if I want to keep using f-strings.

Also why does the warning exist in the first place, I'd expect bytes to be printed as the b"..." honestly and it seems weird for a type checking tool to warn me about how formatting works.

**Comment by ajkaijanaho** [comment]
This error message is completely unclear and unactionable.

**Comment by sobolevn** [comment]
@ajkaijanaho do you have suggestions on how to improve it? :)

**Comment by ikonst** [comment]
@Syndace It has a distinct error code `str-bytes-safe` so you can disable it.

This should illustrate how to take the action on this error:
https://mypy-play.net/?mypy=latest&python=3.11&gist=097c14bfe36a2f09487802689904d5f0

@sobolevn I think 'abc' might be confusing, would be nicer if we could "unparse" the user's actual expression there. For example, in my playground that'd be:
```diff
-main.py:3: error: On Python 3 formatting "b'abc'" with "{}" produces "b'abc'", not "abc"; use "{!r}" if this is desired behavior  [str-bytes-safe]
-main.py:5: error: On Python 3 formatting "b'abc'" with "{}" produces "b'abc'", not "abc"; use "{!r}" if this is desired behavior  [str-bytes-safe]
+main.py:3: error: On Python 3 formatting "data" with "{}" produces "b'...'", not "..."; use "{!r}" if this is desired behavior  [str-bytes-safe]
+main.py:5: error: On Python 3 formatting "{data}" produces "b'...'", not "..."; use "{data!r}" if this is desired behavior  [str-bytes-safe]
```

Another thought would be to remove "On Python 3" since I think we're sufficiently far from Python 2.

**Comment by ajkaijanaho** [comment]
> @ajkaijanaho do you have suggestions on how to improve it? :)

I do not understand it, so no. It is not clear to me why it is something that needs to be flagged by mypy, and what problem it solves. Certainly, in the context of where I ran into it, the message was incomprehensible, and Googling came up with no useful documentation (but it did turn up this issue).

> I think 'abc' might be confusing, would be nicer if we could "unparse" the user's actual expression there. For example, in my playground that'd be:

Yes, this makes it clearer, but it does not answer what the recommended action is if that is not the desired behavior.

**Comment by beauxq** [comment]
> Another thought would be to remove "On Python 3" since I think we're sufficiently far from Python 2.

I think removing "on Python 3" would make it MORE confusing, because that would remove context of why the rule exists.
This rule is only relevant in a transition from Python 2 to Python 3.

There are still some people migrating code bases from Python 2 to Python 3. For those people, this rule could help catch an error.

For anyone else, this rule is irrelevant - as pointed out above https://github.com/python/mypy/issues/11806#issuecomment-1081612521

> Also why does the warning exist in the first place, I'd expect bytes to be printed as the b"..." honestly and it seems weird for a type checking tool to warn me about how formatting works.

**Comment by ikonst** [comment]
In a pure Python 3 context, a helpful error message might be something that outlines your options e.g.

`{data}` (or equivalent `"{}".format(data)`) is implicitly getting a `repr` of the bytes.
- If that's your intention, make it explicit by adding `!r` to the format string.
- If you meant to decode the `bytes` to `str`, call `data.decode()`.

Now, whether "printing bytes as if they were a string" is a likely error (especially for devs who didn't come from py2) or mypy nannying the developer is one that's hard to answer. I do think adding `!r` better complies with "explicit is better than implicit" :)

**Comment by beauxq** [comment]
> I do think adding `!r` better complies with "explicit is better than implicit"

Wouldn't that mean that adding `!r` is better for every data type whose `__str__` gives the same result as `__repr__`?

`f"1 2 {3!r}"`

**Comment by ikonst** [comment]
I think it's meant to be a heuristic, i.e. you'd do it for types where you're likely to spot a user error. (Generally, mypy often makes pragmatic decisions, seeing it more as a tool for error-checking than an abstract type-checker.)

**Comment by beauxq** [comment]
I think this is only likely to spot a user error in the context of transitioning from Python 2 to Python 3.
Outside of that context, it's just more likely to cause confusion, because `bytes` is just like a lot of other data types, where `__str__` is the same as `__repr__`.

**Comment by beauxq** [comment]
There are still some people migrating code bases from Python2 to Python3, so it could have a little usefulness for those people.
But I wouldn't think it's worth it to keep maintaining this feature.
People dealing with those migrations are going to have to deal with similar issues on their own anyway.

**Comment by beauxq** [comment]
To be clear, this feature is not for analyzing Python 2 code, so supporting Python 2 isn't really the issue.
It is definitely for Python 3 specifically.

But it's for analyzing Python 3 code:
 - that was migrated from Python 2
 - that was written by people who were used to Python 2, so they follow a pattern they used in Python 2
 - for people who find Python 2 code online, and copy/paste it into their Python 3 project
 - etc.

Some of these will never stop happening. So there will always be some usefulness,, but is it worth it?

**Comment by ajkaijanaho** [comment]
> In a pure Python 3 context, a helpful error message might be something that outlines your options e.g.
> 
> `"{data}"` (or equivalent `"{}".format(data)`) is implicitly getting a `repr` of the bytes.
> 
> * If that's your intention, make it explicit by adding `!r` to the format string.
> * If you meant to decode the `bytes` to `str`, call `data.decode()`.
> 
> Now, whether "printing bytes as if they were a string" is a likely error (especially for devs who didn't come from py2) or mypy nannying the developer is one that's hard to answer. I do think adding `!r` better complies with "explicit is better than implicit" :)

I think. in the rare case where this actually comes up, this advice would be sound. Sometimes people are not really realizing they have a bytes object rather than str. But as this is not a type error (as in, something that would raise an exception at runtime at least some of the time), it's not really something that mypy needs to deal with, and Python is full of such sometimes surprising behavior, bytes being nothing special in that regard.  I would not object to removing this check, but if it is kept, I think the issue should be discussed in the docs (with a pointer in the error message).

**Comment by JukkaL** [comment]
>  I think the issue should be discussed in the docs (with a pointer in the error message).

I agree, and I think that this is the best way to move forward. We should document the error code [here](https://mypy.readthedocs.io/en/stable/error_code_list.html) where we discuss other error codes, and provide example error messages and discuss why we have this check. If this still causing confusion in the future, we can consider turning off the error code by default, but I think that this should happen only some time after we've made the documentation updates.

I also think that forgetting to explicitly encode bytes values is still a somewhat common issue in code that was never intended to be run on Python 2, and mypy catching these can be helpful. The open issue is whether this check should be enabled by default.

**Comment by beauxq** [comment]
> * Except for bytes

This is not an exception. `bytes` can also be converted to `str` as simple as `str(your_bytes)`

This conversion is often what is desired and there's no reason to add `!r` if this is what is desired.

**Comment by ikonst** [comment]
"This conversion is often what is desired" is precisely what's left to be debated: the basis of any lint rule is the ratio of detected errors vs. nuisance to users.

The 'nuisance to users' is what you need to do to mitigate (in this case, adding two characters, which is small relative to other nuisances like adding `# type: ignore`, `assert ...` etc.).

If 'detected errors' is close to nil, then any amount of nuisance is too much, of course.
