### ISSUE TITLE
`TypeGuard` does not correctly narrow down generics

### ISSUE THREAD

**Issue by bibajz** [python/mypy#11907]
**Bug Report**

I wrote a higher-order function which converts a function into a coroutine function and also is idempotent on a coroutine function.

I wanted to try `TypeGuard` as  it seemed to fit this particular use case.

**To Reproduce**

```python
import typing as t

from typing_extensions import ParamSpec, TypeGuard

T = t.TypeVar("T")
P = ParamSpec("P")


def is_awaitable(
    coro_or_value: t.Union[T, t.Awaitable[T]]
) -> TypeGuard[t.Awaitable[T]]:
    return hasattr(coro_or_value, "__await__")


def ensure_async(
    fn: t.Union[t.Callable[P, T], t.Callable[P, t.Awaitable[T]]]
) -> t.Callable[P, t.Awaitable[T]]:
    async def inner(*args: P.args, **kwargs: P.kwargs) -> T:
        coro_or_value = fn(*args, **kwargs)
        if is_awaitable(coro_or_value):
            return await coro_or_value  # mypy says: Incompatible return value type (got "T", expected "T")
        else:
            return coro_or_value  # mypy says: Incompatible return value type (got "Union[T, Awaitable[T]]", expected "T")

    return inner


def add(x: int, y: int) -> int:
    return x + y


async def a_add(x: float, y: float) -> float:
    return x + y


if t.TYPE_CHECKING:
    reveal_type(ensure_async(add))  # Revealed type is "def (*<nothing>, **<nothing>) -> typing.Awaitable[<nothing>]"
    reveal_type(ensure_async(add)(1, 2))  # Revealed type is "typing.Awaitable[<nothing>]"
    reveal_type(ensure_async(a_add))  # Revealed type is "def (*<nothing>, **<nothing>) -> typing.Awaitable[<nothing>]"
```

**Expected Behavior**

- In the case of `Incompatible return value type (got "T", expected "T")`, I would not expect this message.
- In the case of `Incompatible return value type (got "Union[T, Awaitable[T]]", expected "T")`, I would expect that this is what `TypeGuard` is precisely for - knows how to handle the `else` case of type narrowing, so no message.

**Actual Behavior**

Mypy is not able to typecheck. The important errors:

```
2022_01_05_typeguard_mypy_bug.py:21: error: Incompatible return value type (got "T", expected "T")
2022_01_05_typeguard_mypy_bug.py:23: error: Incompatible return value type (got "Union[T, Awaitable[T]]", expected "T")
```

Full mypy log, including the exemplary functions:

```
2022_01_05_typeguard_mypy_bug.py:21: error: Incompatible return value type (got "T", expected "T")
2022_01_05_typeguard_mypy_bug.py:23: error: Incompatible return value type (got "Union[T, Awaitable[T]]", expected "T")
2022_01_05_typeguard_mypy_bug.py:37: note: Revealed type is "def (*<nothing>, **<nothing>) -> typing.Awaitable[<nothing>]"
2022_01_05_typeguard_mypy_bug.py:37: error: Argument 1 to "ensure_async" has incompatible type "Callable[[int, int], int]"; expected "Callable[[VarArg(<nothing>), KwArg(<nothing>)], Awaitable[<nothing>]]"
2022_01_05_typeguard_mypy_bug.py:38: note: Revealed type is "typing.Awaitable[<nothing>]"
2022_01_05_typeguard_mypy_bug.py:38: error: Argument 1 to "ensure_async" has incompatible type "Callable[[int, int], int]"; expected "Callable[[VarArg(<nothing>), KwArg(<nothing>)], Awaitable[<nothing>]]"
2022_01_05_typeguard_mypy_bug.py:38: error: Argument 1 has incompatible type "int"; expected <nothing>
2022_01_05_typeguard_mypy_bug.py:38: error: Argument 2 has incompatible type "int"; expected <nothing>
2022_01_05_typeguard_mypy_bug.py:39: note: Revealed type is "def (*<nothing>, **<nothing>) -> typing.Awaitable[<nothing>]"
2022_01_05_typeguard_mypy_bug.py:39: error: Argument 1 to "ensure_async" has incompatible type "Callable[[float, float], Coroutine[Any, Any, float]]"; expected "Callable[[VarArg(<nothing>), KwArg(<nothing>)], Awaitable[<nothing>]]"
Found 7 errors in 1 file (checked 1 source file)
```
(Write what happened.)

**Your Environment**

- Mypy version used:  0.940+dev.9c05d3d19de74fc10a51aa5b663e6a38bc6abc73
- Python version used: 3.10.1 and 3.9.7

**Comment by A5rocks** [comment]
I think this is fixed by #11797

**Comment by bibajz** [comment]
Hello @A5rocks , I installed mypy directly from the branch you mentioned and I can confirm that

```
error: Incompatible return value type (got "T", expected "T")
```
is gone.

However, all the other errors remain, especially the `else` branch of narrowing:

```
error: Incompatible return value type (got "Union[T, Awaitable[T]]", expected "T")
```

So the error log altogether as of #11797 is

```
2022_01_05_typeguard_mypy_bug.py:23: error: Incompatible return value type (got "Union[T, Awaitable[T]]", expected "T")
2022_01_05_typeguard_mypy_bug.py:39: note: Revealed type is "def (*<nothing>, **<nothing>) -> typing.Awaitable[<nothing>]"
2022_01_05_typeguard_mypy_bug.py:39: error: Argument 1 to "ensure_async" has incompatible type "Callable[[int, int], int]"; expected "Callable[[VarArg(<nothing>), KwArg(<nothing>)], Awaitable[<nothing>]]"
2022_01_05_typeguard_mypy_bug.py:40: note: Revealed type is "typing.Awaitable[<nothing>]"
2022_01_05_typeguard_mypy_bug.py:40: error: Argument 1 to "ensure_async" has incompatible type "Callable[[int, int], int]"; expected "Callable[[VarArg(<nothing>), KwArg(<nothing>)], Awaitable[<nothing>]]"
2022_01_05_typeguard_mypy_bug.py:40: error: Argument 1 has incompatible type "int"; expected <nothing>
2022_01_05_typeguard_mypy_bug.py:40: error: Argument 2 has incompatible type "int"; expected <nothing>
2022_01_05_typeguard_mypy_bug.py:41: note: Revealed type is "def (*<nothing>, **<nothing>) -> typing.Awaitable[<nothing>]"
2022_01_05_typeguard_mypy_bug.py:41: error: Argument 1 to "ensure_async" has incompatible type "Callable[[float, float], Coroutine[Any, Any, float]]"; expected "Callable[[VarArg(<nothing>), KwArg(<nothing>)], Awaitable[<nothing>]]"
Found 6 errors in 1 file (checked 1 source file)
```

**Comment by cdce8p** [comment]
> However, all the other errors remain, especially the `else` branch of narrowing

TypeGuard doesn't support narrowing the else case. There are some feature proposals for it though.
https://github.com/python/typing/issues/996
https://mail.python.org/archives/list/typing-sig@python.org/thread/EMUD2D424OI53DCWQ4H5L6SJD2IXBHUL/

**Comment by bibajz** [comment]
@cdce8p

Ok, thank you for clarification and further links. Definitely an interesting read and I am looking forward for future development!

Closing this issue for redundancy and also because a fix for the positive case is already done - #11797

**Comment by goodoldneon** [comment]
Running into this problem, too.

I get these errors:

```
main.py:23: note: Revealed type is "builtins.list[Any]"
main.py:26: note: Revealed type is "builtins.list[T`-1]"
main.py:27: error: Argument 1 to "do_stuff" has incompatible type "List[T]"; expected "List[Foo]"
Found 1 error in 1 file (checked 1 source file)
```

When I run this code:

```py
from typing import Any, TypeGuard, Type, TypeVar

def do_stuff(foos: list[Foo]) -> None:
    pass

class Foo:
    pass

T = TypeVar("T")

def is_list_of(value: list, type: Type[T]) -> TypeGuard[list[T]]:
    for item in value:
        if isinstance(item, type) is False:
            return False

    return True

foos: list[Any] = [Foo()]
reveal_type(foos)

if is_list_of(foos, Foo):
    reveal_type(foos)
    do_stuff(foos)
```

I'm really excited about the recent Mypy work! I've been using Mypy for the last couple years and y'all have made some amazing progress. Thanks so much for this awesome project
