### ISSUE TITLE
Mypy failed to recognize parameter and return types in lambda functions

### ISSUE THREAD

**Issue by max-hk** [python/mypy#11994]
**Bug Report**

Mypy should be able to recognize parameter and return types of a lambda functions from the context. (like lambda functions passed as aguments to `map` or `filter`)

**To Reproduce**

```py
from typing import List

class SampleClass:
    an_attribute: int

foo: List[SampleClass] = []

bar = map(lambda an_instance: an_instance.an_attribute, foo)
```

**Expected Behavior**

mypy should infer the type of `an_instance` to be `SampleClass` and the lambda function to be `Callable[[SampleClass], int]`

**Actual Behavior**

Mypy reported the following error.

```
a.py:8: error: Expression type contains "Any" (has type "Callable[[Any], Any]")
```

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: `$ mypy --disallow-any-unimported --disallow-any-expr --disallow-any-explicit --disallow-any-generics --disallow-subclassing-any a.py`
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.6.8
- Operating system and version: Window 11

**Comment by erictraut** [comment]
This bug appears to have been fixed. The latest version of mypy (1.5) no longer exhibits an error, and it properly evaluates the type of the expression in the code sample above.

**Comment by hauntsaninja** [comment]
I do still get the error with `--disallow-any-expr`. I think that flag is too pedantic to be useful, but in this case it is behaving as intended.
