### ISSUE TITLE
re.sub doesn't work with compiled pattern

### ISSUE THREAD

**Issue by sharmaeklavya2** [python/mypy#1460]
I don't know whether this is a bug in typeshed or mypy, so I'm posting it here. I'll post it again on typeshed if needed.

This works:
```py
import re
print(re.sub("abc", "def", input()))
```

But this doesn't:
```py
import re
print(re.sub(re.compile("abc"), "def", input()))
```
```
regex_fail.py:2: error: Type argument 1 of "sub" has incompatible value "object"
```

**Comment by gvanrossum** [comment]
Can you still repro this with the latest version from github? I think we fixed this.

**Comment by sharmaeklavya2** [comment]
I had tried it out with the master branch of the latest version from github. The error is still there.

**Comment by gvanrossum** [comment]
Looks like a typeshed error.

**Comment by rwbarton** [comment]
Agreed, and there is already an issue for it on typeshed: https://github.com/python/typeshed/issues/160.
