### ISSUE TITLE
Mypy 1.4 Release Planning

### ISSUE THREAD

**Issue by jhance** [python/mypy#15372]
I'm planning to make a 1.4 release around early July. (This is actually meant to be the June release but it is delayed).

Please post here any issues you'd like to see fixed in the release, or PRs you'd like to have merged. The release branch is available as release-1.4.

**Comment by cdce8p** [comment]
The mypy wheel build seems to be broken atm. It seems to be platform specific to `x86_64`, `arm64` isn't affected. More details: https://github.com/python/mypy/issues/15283#issuecomment-1578609223

_Cross posting it here to keep track._

**Comment by AlexWaygood** [comment]
- @A5rocks's PR here purports to fix two open crash reports: #15272
- It's not urgent, but I'd love it if  somebody could take a look at my PR here. It's been open >2 months now, it's not too complicated, and the primer results look good: #14988

**Comment by AlexWaygood** [comment]
Also, just to note: #15161 caused a LiteralString-related regression for typeshed that still exists on the master branch. I reported the regression here immediately after the PR was merged: https://github.com/python/mypy/pull/15161#issuecomment-1531596612.

It looks like it's probably a typeshed-specific problem, and we can definitely just work around it in typeshed if we need to. So it's not a huge issue by any means. Just thought I'd mention it anyway, though!

**Comment by ilevkivskyi** [comment]
I going to work on some recently reported crashes. I will post them here as soon as I have a fix, the first will be https://github.com/python/mypy/issues/15351

**Comment by ilevkivskyi** [comment]
And here is a fix for this crash https://github.com/python/mypy/pull/15402

**Comment by ilevkivskyi** [comment]
And here is a fix for another crash https://github.com/python/mypy/pull/15403

**Comment by ilevkivskyi** [comment]
And yet another crash fix https://github.com/python/mypy/pull/15404

**Comment by hauntsaninja** [comment]
Two crash fixes of mine that didn't make the branch: #15392 #15399

**Comment by ilevkivskyi** [comment]
And here is yet another crash fix https://github.com/python/mypy/pull/15407

**Comment by cdce8p** [comment]
Would love to see #15413 included. That change alone removes 23 unnecessary `type: ignore` comments in Home Assistant.

**Comment by intgr** [comment]
@ymyzk Can you please add mypy 1.4.0 to mypy-play.net?

**Comment by ymyzk** [comment]
@intgr It should be available on mypy Playground now: https://github.com/ymyzk/mypy-playground/pull/388

**Comment by hauntsaninja** [comment]
Thanks for all the work! Regression for asyncio here #15489 with a potential fix here #15491. This will need a hotfix release (I can make it if you're busy)

**Comment by ilevkivskyi** [comment]
Wait, so this is already released? Is it early July already? What was the point to not include the stable error code links in the release?

**Comment by JukkaL** [comment]
This was the postponed May mypy release. I think stable error code links arrived too late in the release process, but there will be a 1.5 release in July (targeting early July). @svalentin is the RM for 1.5.

**Comment by cdce8p** [comment]
In case there is a `1.4.1` release. These fix the wheel build
- [ ] #15451
- [ ] #15493

Fix for `typing_extensions` dependency issue
- [ ] #15488

**Comment by AlexWaygood** [comment]
You'll probably also want to cherry-pick this, if there is a 1.4.1 release:

- [ ] https://github.com/python/mypy/pull/15505

**Comment by hauntsaninja** [comment]
I've cherry picked the following to the 1.4 release branch:

Fix for async type checking regression
```
f36ea01e9 (HEAD -> release-1.4) Shantanu: Fix async iterator body stripping (#15491)      (Fri Jun 23 18:12:13 2023)
```
A fix for typeshed (reverts a PR that fixed another problem that only manifested on typeshed)
```
ba7887be3             Shantanu: Revert "Fix spurious errors on builtins.open (#15161)" (#15508) (Fri Jun 23 18:12:10 2023)
```
Docs changes:
```
16fe5da0b      Ivan Levkivskyi: Fix readthedocs build (#15437)                            (Fri Jun 23 17:54:30 2023)
9b327d12b      Ivan Levkivskyi: Use consistent anchors for error codes (#15435)           (Fri Jun 23 17:54:26 2023)
32abe0210          Ilya Priven: docs: ref redirector (#15432)                             (Fri Jun 23 17:54:14 2023)
```
Fixes for CI and wheel build:
```
e5a5b33e1         Alex Waygood: Unbreak CI (#15505)                                       (Fri Jun 23 17:39:48 2023)
81d01aa0b         Marc Mueller: Fix PEP 561 editable install test case (#15493)           (Fri Jun 23 17:39:30 2023)
eba351e40         Marc Mueller: Add pip as test requirement for PEP 660 editable installs (#15482) (Fri Jun 23 17:39:26 2023)
9faffe87c         Marc Mueller: Bump typing_extensions dependency (#15488)                (Fri Jun 23 17:39:21 2023)
7871ed92a             Shantanu: Switch PEP 561 tests to a different build backend (#15451) (Fri Jun 23 17:39:16 2023)
87ddfeeef         hauntsaninja: Add back +dev to version                                  (Fri Jun 23 17:38:45 2023)
```

Hopefully this is all good. If I don't hear anything, I'll make a patch release this weekend (really excited to have the 1.4 speedups at work)

**Comment by hauntsaninja** [comment]
I've released mypy 1.4.1

**Comment by Avasam** [comment]
Was #15429 actually included in 1.4.1 ? I still have the issue where `--ignore-missing-imports` causes
```
Restarting: configuration changed
Daemon stopped
Daemon started
```

**Comment by svalentin** [comment]
I don't see it in https://github.com/python/mypy/commits/release-1.4
It will definitely be in release 1.5

**Comment by intgr** [comment]
The mypy website https://www.mypy-lang.org/ still hasn't been updated to list version 1.4.
