### ISSUE TITLE
Too many arguments for __init_subclass__

### ISSUE THREAD

**Issue by philtay** [python/mypy#4660]
The annotated version of this simple [example](https://docs.python.org/3/reference/datamodel.html#customizing-class-creation) fails validation:

```python
class Philosopher:
    def __init_subclass__(cls, default_name: str, **kwargs) -> None:
        super().__init_subclass__(**kwargs)
        cls.default_name = default_name

class AustralianPhilosopher(Philosopher, default_name="Bruce"):
    pass
```

Error message: `foo.py:3: error: Too many arguments for "__init_subclass__" of "object"`. Note that the call to `super()` is necessary.

**Comment by gvanrossum** [comment]
Ooh, yeah, mypy doesn't seem to understand enough about `__init_subclass__`.

**Comment by andymwood** [comment]
I've just encountered the same error when calling `super().__int__(arg)` in a class that inherits from `collections.UserDict`.

Is this the same bug, or should I raise another issue for that?

**Comment by ilevkivskyi** [comment]
> Is this the same bug, or should I raise another issue for that?

IIRC `UserDict` was just a typeshed problem and was fixed few months ago, you should update mypy.

**Comment by andymwood** [comment]
> IIRC UserDict was just a typeshed problem and was fixed few months ago, you should update mypy.

I've just tried v0.610. That appears to have fixed the problem.

Thank you.

**Comment by ttung** [comment]
Is there a way to suppress this particular error?  `# type: ignore` doesn't seem to work for this.

**Comment by mjpieters** [comment]
> Is there a way to suppress this particular error? `# type: ignore` doesn't seem to work for this.

You need to put it on the right line :-) It's the `super()` call that mypy complains about. This works:

```python
class Philosopher:
    def __init_subclass__(cls, default_name: str, **kwargs) -> None:
        super().__init_subclass__(**kwargs)  # type: ignore
        cls.default_name = default_name
```

**Comment by ttung** [comment]
Ah ha!  I didn't put it on the right line.  Also, hi @mjpieters! :)

**Comment by dhorkin** [comment]
I'm having this issue when I use mypy 0.740, but not 0.730, so it sounds like there was a regression.

**Comment by JukkaL** [comment]
@dhorkin Can you provide a code fragment that illustrates the difference between 0.730 and 0.740? The original example seems to work the same on 0.730 and 0.740.

**Comment by dhorkin** [comment]
Toy example:
```
from dataclasses import dataclass

@dataclass(order=True, frozen=True)
class Base:
    def __init_subclass__(cls, *args, **kwargs):
        super().__init_subclass__(*args, **kwargs)

@dataclass(order=True, frozen=True)
class Sub1(Base):
    a: str
    b: str
```

Passes 0.730 but fails 0.740

**Comment by sergiorussia** [comment]
even without dataclass:
```python
class Base:
    def __init_subclass__(cls, *args, **kwargs):
        super().__init_subclass__(*args, **kwargs)

class Derived(Base):
    pass
```
```
%  mypy test.py
test.py: note: In class "Derived":
test.py:5:1: error: Too few arguments for "__init_subclass__"
Found 1 error in 1 file (checked 1 source file)
%  mypy --version
mypy 0.740
```
```
%  mypy test.py
Success: no issues found in 1 source file
%  mypy --version
mypy 0.730
```

**Comment by vikigenius** [comment]
The issue still persists for me with the same example and it never goes away irrespective of the version

```
# -*- coding: utf-8 -*-

class Base:
    def __init_subclass__(cls, *args, **kwargs):
        super().__init_subclass__(*args, **kwargs)

class Derived(Base):
    pass
```

``` 
% mypy example.py
example.py:5: error: Too many arguments for "__init_subclass__" of "object"
```

The same error shows up for me even in 0.730, 0.740, 0.782. What's the difference, how can the behavior be different for me compared to @sergiorussia  even when I use the same version of mypy?

**Comment by MrMrRobat** [comment]
@vikigenius, same here on Python 3.9 and mypy 0.790 😕

**Comment by leoruiz** [comment]
Same for me on Python 3.9.1 and mypy 0.800

**Comment by ahopkins** [comment]
Same on **Python 3.9.3** and **mypy 0.812**

**Comment by 97littleleaf11** [comment]
I cannot reproduce it. Maybe it has been fixed? cc @vikigenius @Bobronium @leoruiz @ahopkins

**Comment by mwchase** [comment]
Looks like this was fixed between .910 and .920.

**Comment by vikigenius** [comment]
@97littleleaf11 @mwchase 
I can still reproduce this with `check_untyped_defs` enabled:

```python
class Base:
    def __init_subclass__(cls, *args, **kwargs):
        super().__init_subclass__(*args, **kwargs)

class Derived(Base):
    pass
```

`mypy example.py --check-untyped-defs`

`example.py:3: error: Too many arguments for "__init_subclass__" of "object"`

The check-untyped-defs is probably required because I haven't annotated the function.

**Comment by 97littleleaf11** [comment]
Can you try on latest release or master branch? @vikigenius

**Comment by mwchase** [comment]
I meant, I can reproduce it on .910 but not .920.

**Comment by vikigenius** [comment]
Ok, I couldn't reproduce in 0.920 either, must have been fixed since then.
